# Generated by Django 5.2.5 on 2025-10-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='digital_home',
            field=models.JSONField(default=list),
        ),
    ]
