# Generated by Django 5.2.5 on 2025-10-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff_staff'),
        ('users', '0004_customer_digital_home'),
    ]

    operations = [
    ]
