# Generated by Django 5.2.5 on 2025-10-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20251014_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profilePic',
            new_name='profile_pic',
        ),
    ]
