# Generated by Django 5.2.5 on 2025-10-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profilepic_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_token', models.CharField(max_length=255, unique=True)),
                ('account_holder', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts_rel', to='users.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='users_banka_custome_99bdf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_token', models.CharField(max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards_rel', to='users.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='users_credi_custome_e95f6d_idx'), models.Index(fields=['provider', 'provider_token'], name='users_credi_provide_007a63_idx')],
            },
        ),
    ]
