# Generated by Django 5.2.5 on 2025-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bankaccount_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
