# Generated by Django 5.2.5 on 2025-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.JSONField(default=list),
        ),
    ]
