# Generated by Django 5.2.7 on 2025-11-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentmethod_order_payment_method'),
        ('users', '0009_remove_customer_wishlist_id_customer_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_account_last4',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='credit_card_last4',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bankaccount'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.creditcard'),
        ),
    ]
