# Generated by Django 5.2.7 on 2025-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_paymentmethod_bank_account_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='order',
        ),
    ]
