# Generated by Django 5.2.5 on 2025-10-14 08:55

import app_api.products.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', app_api.products.models.PointZMField(dim=4, srid=4979)),
                ('rotation', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('scale', models.FloatField(default=1.0)),
                ('texture_id', models.IntegerField(blank=True, null=True)),
                ('position_history', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('digital_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('physical_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('stock', models.IntegerField()),
                ('reviews', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonContainerOwnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.JSONField(default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_container', to='products.ownedproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerOwnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained_product', models.JSONField(default=list)),
                ('products', models.ManyToManyField(related_name='containers', to='products.ownedproducts')),
            ],
        ),
        migrations.AddField(
            model_name='ownedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to='products.product'),
        ),
    ]
