# Generated by Django 5.2.5 on 2025-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_scenes',
            field=models.JSONField(default=list),
        ),
    ]
