# Generated by Django 5.2.5 on 2025-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_digital_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='physical_available',
            field=models.BooleanField(default=False),
        ),
    ]
