# Generated by Django 5.2.5 on 2025-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
