# Generated by Django 5.2.5 on 2025-10-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerownedproducts',
            name='products',
        ),
        migrations.AddField(
            model_name='containerownedproducts',
            name='products',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='products.ownedproducts'),
            preserve_default=False,
        ),
    ]
