# Generated by Django 5.2.5 on 2025-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_containerownedproducts_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerownedproducts',
            old_name='products',
            new_name='product',
        ),
    ]
