# Generated by Django 5.2.5 on 2025-10-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_products_containerownedproducts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedproducts',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
