# Generated by Django 5.2.5 on 2025-10-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_ownedproducts_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('is_container', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_container',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_products', to='products.item'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='ContainerOwnedProducts',
            new_name='ContainerOwnedItem',
        ),
        migrations.RenameModel(
            old_name='NonContainerOwnedProducts',
            new_name='NonContainerOwnedItem',
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.JSONField(default=dict)),
                ('rotation', models.JSONField(default=dict)),
                ('scale', models.JSONField(default=dict)),
                ('texture_id', models.IntegerField(blank=True, null=True)),
                ('position_history', models.JSONField(default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='products.item')),
            ],
        ),
        migrations.AlterField(
            model_name='containerowneditem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='products.owneditem'),
        ),
        migrations.AlterField(
            model_name='noncontainerowneditem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_container', to='products.owneditem'),
        ),
        migrations.DeleteModel(
            name='OwnedProducts',
        ),
    ]
