# Generated by Django 5.2.5 on 2025-10-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_item_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerowneditem',
            old_name='contained_product',
            new_name='contained_item',
        ),
        migrations.RenameField(
            model_name='containerowneditem',
            old_name='product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='noncontainerowneditem',
            old_name='product',
            new_name='item',
        ),
    ]
