# Generated by Django 5.2.5 on 2025-10-30 03:40

import app_api.products.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_product_cartitem_product_id'),
        ('orders', '0003_remove_orderitem_product_orderitem_product_id'),
        ('products', '0010_rename_contained_product_containerowneditem_contained_item_and_more'),
        ('reviews', '0003_remove_review_product_review_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', app_api.products.models.PointZMField(dim=4, srid=4979)),
                ('rotation', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('scale', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('position_history', models.JSONField(default=list)),
                ('pivot', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('mesh_data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='owneditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.RemoveField(
            model_name='noncontainerowneditem',
            name='item',
        ),
        migrations.DeleteModel(
            name='ContainerOwnedItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='NonContainerOwnedItem',
        ),
        migrations.DeleteModel(
            name='OwnedItem',
        ),
    ]
