# Generated by Django 5.2.5 on 2025-10-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_spatialdata_remove_owneditem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialdata',
            name='mesh_data',
        ),
        migrations.RemoveField(
            model_name='spatialdata',
            name='pivot',
        ),
    ]
