rooms_data = {
    "livingroom": {
        "title": "Living Room",
        "image": "/images/livingroom.jpg",
        "categories": ["Tables", "Sofas", "Decor"],
        "products": [
            {
                "title": "Modern Luxury Sofa",
                "category": "Sofa",
                "physical_price": 1299,
                "digital_price": 99,
                "rating": 4.8,
                "model_url": "/models/antique_table.glb",
                "image": "/images/longsofa.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Mini Cute Puff",
                "category": "Puffs",
                "physical_price": 2999,
                "digital_price": 149,
                "rating": 4.7,
                "model_url": "/models/luxury_sofa.glb",
                "image": "/images/puff.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Modern Luxury Sofa",
                "category": "Sofa",
                "physical_price": 1299,
                "digital_price": 99,
                "rating": 4.8,
                "model_url": "/models/antique_table.glb",
                "image": "/images/longsofa.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detailt",
            },

        ],
    },
    "bedroom": {
        "title": "Bedroom",
        "image": "/images/bedroom.jpg",
        "categories": ["Bedside Tables", "Wardrobes", "Lighting"],
        "products": [
            {
                "title": "Bedside Tables",
                "category": "Beds",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/bedsidetable.jpg",
                "hover_image": "/images/room.jpg",
                "link": "/product_detail",
            },
               {
                "title": "Bedside Tables",
                "category": "Beds",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/bedsidetable.jpg",
                "hover_image": "/images/room.jpg",
                "link": "/product_detail",
            },
               {
                "title": "Bedside Tables",
                "category": "Beds",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/bedsidetable.jpg",
                "hover_image": "/images/room.jpg",
                "link": "/product_detail",
            },
            
        ],
    },
    "kitchen": {
        "title": "Kitchen",
        "image": "/images/kitchenroom.jpg",
        "categories": ["Fridges", "Cabinets", "Utensils"],
        "products": [
            {
                "title": "Fridges",
                "category": "Fridges",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/fridge.jpg",
                "hover_image": "/images/bed_hover.png",
                "link": "/product_detail",
            },
            {
                "title": "Fridges",
                "category": "Fridges",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/fridge.jpg",
                "hover_image": "/images/bed_hover.png",
                "link": "/product_detail",
            },
            {
                "title": "Fridges",
                "category": "Fridges",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/fridge.jpg",
                "hover_image": "/images/bed_hover.png",
                "link": "/product_detail",
            },
          
        ],
    },

    "officeroom": {
        "title": "Office Room",
        "image": "/images/officeroom.jpg",
        "categories": ["Tables", "Chairs", "Desks"],
        "products": [
            {
                "title": "Modern Office Chair",
                "category": "Chairs",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/modernChair.jpg",
                "hover_image": "/images/officeroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Modern Office Chair",
                "category": "Chairs",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/modernChair.jpg",
                "hover_image": "/images/officeroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Modern Office Chair",
                "category": "Chairs",
                "physical_price": 4999,
                "digital_price": 199,
                "rating": 4.9,
                "model_url": "/models/queen_bed.glb",
                "image": "/images/modernChair.jpg",
                "hover_image": "/images/officeroom.jpg",
                "link": "/product_detail",
            },
        ],
    },
}


products = [
            {
                "title": "Modern Luxury Sofa",
                "category": "Sofa",
                "physical_price": 1299,
                "digital_price": 99,
                "rating": 4.8,
                "model_url": "/models/antique_table.glb",
                "image": "/images/longsofa.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Modern Luxury Sofa",
                "category": "Sofa",
                "physical_price": 1299,
                "digital_price": 99,
                "rating": 4.8,
                "model_url": "/models/antique_table.glb",
                "image": "/images/puff.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detail",
            },
            {
                "title": "Modern Luxury Sofa",
                "category": "Sofa",
                "physical_price": 1299,
                "digital_price": 99,
                "rating": 4.8,
                "model_url": "/models/antique_table.glb",
                "image": "/images/fridge.jpg",
                "hover_image": "/images/livingroom.jpg",
                "link": "/product_detail",
            },
]